name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install deps ğŸ”§
        run: npm ci

      - name: Lint ğŸ”
        run: npm run lint
      
      - name: Print key
        run: echo "$REACT_APP_API_KEY"

      - name: Print envs
        run: env
      
      - name: Build ğŸ—ï¸
        run: npm run build
      
      - name: Upload artifacts ğŸ“¤
        uses: actions/upload-artifact@main
        with:
          name: build artifacts
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Download artifacts ğŸ“¥
        uses: actions/download-artifact@main
        with:
          name: build artifacts
          path: build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build
